# -*- coding: utf-8 -*-
"""Data Challenge: Crop Mapping using remote sensing data and machine learning techniques.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CxeNYxOO2x8KOk2SBeNfNlYwDfOdURnA

# **Data Challenge: Crop Mapping using remote sensing data and machine learning techniques ***

---

**By Musbaudeen Ibrahim Olaitan**
"""

#Importing required library

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from tensorflow.keras.models import load_model
from sklearn.metrics import accuracy_score

"""## **Step 1** :Loading the dataset

"""

data = pd.read_csv('/content/drive/MyDrive/ReSAKSS data challenge/Data - 2024 ReSAKSS Data Challenge/real_Dataset_Sen_GB_Challenge.csv')

"""## **Step 2**: Exploring the dataset"""

type(data)

data.shape

"""## **Note:**
**We have 205 rows and 58 columns**
"""

data.columns

data.head()

#Exploring the crop_type in the dataset
data['Crop_type'].unique()

#Cleaning the Crop_type column in the dataset, all data input that has Arachide-Niebe should be represented as Groundnut
data['Crop_type'].replace('Arachide - Niebe', 'Groundnut', inplace=True)
data['Crop_type'].replace('Arachide', 'Groundnut', inplace=True)
data['Crop_type'].replace('Niebe', 'Groundnut', inplace=True)

data.head()

data['Crop_type'].unique()

data['Crop_type'].replace('Pasteque', 'Not groundnut', inplace=True)
data['Crop_type'].replace('Oseille', 'Not groundnut', inplace=True)
data['Crop_type'].replace('Sorgho', 'Not groundnut', inplace=True)
data['Crop_type'].replace('Mil - Sorgho', 'Not groundnut', inplace=True)
data['Crop_type'].replace('Mil', 'Not groundnut', inplace=True)
data['Crop_type'].replace('Mil - Mais', 'Not groundnut', inplace=True)
data['Crop_type'].replace('Verger', 'Not groundnut', inplace=True)
data['Crop_type'].replace('Mais', 'Not groundnut', inplace=True)

data['Crop_type'].unique()

data.head()

#Now we want to convert the crop_type column data to numeral representation, where groundnut is represented as (1) and Not groundnut is represented by (0)
data['Crop_type'].replace('Groundnut', 1, inplace=True)
data['Crop_type'].replace('Not groundnut', 0, inplace=True)

data.head()

"""**HINT**

Now we have cleaned our dataset and we have converted our crop_types column to numeric representation where Groundnut is represented has (1) and Not groundnut is represneted by (0)
"""

#Now we want to check the blank cells in ur data

data.isna().sum()

"""# **Insight**
We can see that there is no blank cells in the columns of our dataset, Now we are goo to go for our third step which is step 3

# **STEP 3**: Data modelling and prediction with continous data
"""

data.columns

x= data [['Pixel_Id', 'BLUE_2023-07-31', 'GREEN_2023-07-31', 'RED_2023-07-31',
       'NIR_2023-07-31', 'WDRVI_2023-07-31', 'NDVI_2023-07-31',
       'MTCI_2023-07-31', 'SNDVI_2023-07-31', 'CI_2023-07-31',
       'PSRI_2023-07-31', 'EVI_2023-07-31', 'SAVI_2023-07-31',
       'BLUE_2023-08-15', 'GREEN_2023-08-15', 'RED_2023-08-15',
       'NIR_2023-08-15', 'WDRVI_2023-08-15', 'NDVI_2023-08-15',
       'MTCI_2023-08-15', 'SNDVI_2023-08-15', 'CI_2023-08-15',
       'PSRI_2023-08-15', 'EVI_2023-08-15', 'SAVI_2023-08-15',
       'BLUE_2023-09-29', 'GREEN_2023-09-29', 'RED_2023-09-29',
       'NIR_2023-09-29', 'WDRVI_2023-09-29', 'NDVI_2023-09-29',
       'MTCI_2023-09-29', 'SNDVI_2023-09-29', 'CI_2023-09-29',
       'PSRI_2023-09-29', 'EVI_2023-09-29', 'SAVI_2023-09-29',
       'BLUE_2023-10-29', 'GREEN_2023-10-29', 'RED_2023-10-29',
       'NIR_2023-10-29', 'WDRVI_2023-10-29', 'NDVI_2023-10-29',
       'MTCI_2023-10-29', 'SNDVI_2023-10-29', 'CI_2023-10-29',
       'PSRI_2023-10-29', 'EVI_2023-10-29', 'SAVI_2023-10-29']]

y= data ['Crop_type']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

#data scaling
scaler = StandardScaler()
x_train_scaled= scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

accuracy_list =[] #This is a list to save all the values from different models accuracy for comparison using a bar chart

"""# **3.1 Logistics Regression**"""

lr_model = LogisticRegression()
lr_model.fit(x_train_scaled, y_train)
lr_prediction = lr_model.predict(x_test_scaled)
lr_accuracy =(round(accuracy_score(lr_prediction, y_test), 4) *100) #percentage
accuracy_list.append(lr_accuracy)

"""# **3.2 Support Vector Machine**"""

svc_model = SVC()
svc_model.fit(x_train_scaled, y_train)
svc_prediction = svc_model.predict(x_test_scaled)
svc_accuracy= (round(accuracy_score(svc_prediction, y_test), 4) *100) #percentage
accuracy_list.append(svc_accuracy)

"""# **3.3 Decision Tree Classifier**"""

dt_model = DecisionTreeClassifier(criterion="entropy", max_depth=2)
dt_model.fit(x_train_scaled, y_train)
dt_prediction= dt_model.predict(x_test_scaled)
dt_accuracy= (round(accuracy_score(dt_prediction, y_test), 4) *100) #percentage
accuracy_list.append(dt_accuracy)

"""# **3.4 Naive Bayes**"""

nb_model = GaussianNB()
nb_model.fit(x_train_scaled, y_train)
nb_prediction= nb_model.predict(x_test_scaled)
nb_accuracy= (round(accuracy_score(nb_prediction, y_test), 4) *100) #percentage
accuracy_list.append(nb_accuracy)

"""# **3.5 Random Forest Classifier**"""

rf_model = RandomForestClassifier()
rf_model.fit(x_train_scaled, y_train)
rf_prediction= rf_model.predict(x_test_scaled)
rf_accuracy= (round(accuracy_score(rf_prediction, y_test), 4) *100) #percentage
accuracy_list.append(rf_accuracy)

"""# **3.6 Gradient Boosting Machines**"""

#model for Gradient Boosting Machines
gb_model = GradientBoostingClassifier()
gb_model.fit(x_train_scaled, y_train)
gb_prediction= gb_model.predict(x_test_scaled) # Call predict to get predicted values
gb_accuracy= (round(accuracy_score(gb_prediction, y_test), 4) *100) #percentage
accuracy_list.append(gb_accuracy)

accuracy_list

models = ['Logistic Regression', 'Support Vector Machine', 'Decision Tree Classifier', 'Naive Bayes', 'Random Forest Classifier', 'Gradient Boosting Machines']

plt.figure(figsize=(12,7))
ax = sns.barplot(x=models, y=accuracy_list)
plt.xlabel("Classifiers", fontsize=15)
plt.ylabel("Accuracy (%)", fontsize=15)
for p in ax.patches:
  width = p.get_width()
  height = p.get_height()
  x=p.get_x()
  y=p.get_y()
  ax.annotate(f"{height}%", (x + width/2, y + height*1.01), ha="center")
plt.show()

#Test prediction with challenge data to ascertain the reliability
input_data = (
258,0.8186147616497051,0.7346537546866632,0.6781677557579003,0.6901555865024099,0.0049166041775093,0.0087806230261775,-0.8418684361047069,0.0078594824250401,-0.0087806230261775,-0.2034735142690872,2.440855497713716,0.0042845385113276,0.0788711515800749,0.1400515050883771,0.1231240921264059,0.4226379860739153,0.4936368352549426,0.5523086893031933,2.3265352546525566,0.4263532760769601,-0.5523086893031933,0.1049034649476704,2.793559708630265,0.1914915241631071,0.0461433047670058,0.1022443706480985,0.0800460632029994,0.3647649276914836,0.6545499171043071,0.6444320613926612,2.3434333203797424,0.4728639563975316,-0.6444320613926612,0.0941306499242197,2.800549368573695,0.2014096377190631,0.0502283663631494,0.0924502517407605,0.0718246063202999,0.3639855168719871,0.6817941381582389,0.671185212473161,2.5658593734877067,0.4906538881523895,-0.671185212473161,0.0598574124329615,2.826332382896477,0.2081781879472908 )
# changing the input_data to numpy array
input_data_as_numpy_array= np.asarray(input_data)

# reshaping the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardizing the input data
std_data= scaler.transform(input_data_reshaped)
print(std_data)

prediction = gb_model.predict(std_data)
print(prediction)

if (prediction[0]==1):
  print ("Groundnut")
else:
  print("Not groundnut")

df_predict_file = pd.read_csv("/content/drive/MyDrive/ReSAKSS data challenge/Data - 2024 ReSAKSS Data Challenge/real Dataset_Sen_GB_Challenge_to_predict.csv")

df_predict_file.head()

#Deleting column titled Unnamed: 49 from the df_predict_file
del df_predict_file['Unnamed: 49']

df_predict_file.head()

#Deleting column titled Unnamed: 49 from the df_predict_file
del df_predict_file['Crop_type']

data_list = df_predict_file.values.tolist()

# Test prediction with challenge data to ascertain the reliability
input_data = data_list

# List to store predictions
predictions_list = []

# Iterate over each set of input data and predict the outcome
for data in input_data:
    # Convert the list to a numpy array
    input_data_as_numpy_array = np.asarray(data)

    # Reshape the array as we are predicting for one instance
    input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)

    # Standardize the input data
    std_data = scaler.transform(input_data_reshaped)

    # Make the prediction
    prediction = gb_model.predict(std_data)

    # Append the result to the predictions list
    predictions_list.append(prediction[0])

# Output the list of predictions
print(predictions_list)

# Optionally, convert the numerical predictions to corresponding crop names
crop_names = ["Not groundnut", "Groundnut"]
prediction_labels = [crop_names[p] for p in predictions_list]
print(prediction_labels)

df_predict_file.head()

df_predict_file.shape

df_1= pd.DataFrame(predictions_list, columns=['Crop_type'])
df_2= pd.DataFrame(prediction_labels, columns=['Crop_type_label'])

df_1

df_2

Final_prediction_data= pd.concat([df_predict_file, df_1,df_2], axis=1)

Final_prediction_data

Final_result= Final_prediction_data[['pixel_Id', 'Crop_type_label']]

Final_result

df = pd.DataFrame(Final_result)

# Export to Excel
df.to_excel('/content/drive/MyDrive/DATASETS/prediction_result.xlsx', index=False)

